##################################################
# $Id: .zshrc,v 1.1 2007/10/27 19:05:57 dope Exp $
# 
# README!
# 
# Filename       : ~/.zshrc
# Purpose        : setup file for the shell 'zsh'
# Author         : Christian Schneider <strcat@gmx.net>
# Homepage       : http://www.strcat.de/zsh/
# Latest release : <http://strcat.de/dotfiles/>
#
# Structure of this file:
#  Lines starting with '#' are comments.
#
# Take a quick (haha) look on zshbuiltins(1), zshcompwid(1),
# zshcompsys(1), zshcompctl(1), zshexpn(1), zshmisc(1), zshmodules(1),
# zshoptions(1), zshparam(1), zshzle(1) or - for hardliner -
# zshall(1).
#  ,----[ Overview (Zsh 4.2.6) ]
#  | [dope@painless:~ :) ]% man -k zsh
#  | zsh                  (1)  - the Z shell (384 lines)
#  | zshall               (1)  - the Z shell meta-man page (19841 lines)
#  | zshbuiltins          (1)  - zsh built-in commands (1756 lines) 
#  | zshcompctl           (1)  - zsh programmable completion (593 lines)
#  | zshcompsys           (1)  - zsh completion system (4095 lines)
#  | zshcompwid           (1)  - zsh completion widgets (1026 lines)
#  | zshcontrib           (1)  - user contributions to zsh (1478 lines)
#  | zshexpn              (1)  - zsh expansion and substitution (1613 lines)
#  | zshmisc              (1)  - everything and then some (1474 lines)
#  | zshmodules           (1)  - zsh loadable modules (2443 lines)
#  | zshoptions           (1)  - zsh options (1077 lines)
#  | zshparam             (1)  - zsh parameters (1007 lines)
#  | zshtcpsys            (1)  - zsh tcp system (720 lines)
#  | zshzftpsys           (1)  - zftp function front-end (614 lines)
#  | zshzle               (1)  - zsh command line editor (1575 lines)
#  | [dope@painless:~ :) ]%
#  `----
#  
# Zsh start up sequence:
#  1) /etc/zshenv   -> Always run for every zsh.   (login + interactive + other)
#  2)   ~/.zshenv   -> Usually run for every zsh.  (login + interactive + other)
#  3) /etc/zprofile -> Run for login shells.       (login)
#  4)   ~/.zprofile -> Run for login shells.       (login)
#  5) /etc/zshrc    -> Run for interactive shells. (login + interactive)
#  6)   ~/.zshrc    -> Run for interactive shells. (login + interactive)
#  7) /etc/zlogin   -> Run for login shells.       (login)
#  8)   ~/.zlogin   -> Run for login shells.       (login)
#
# Last modified: [ 2008-11-25 00:26:47 ]
#
#
# THIS FILE IS NOT INTENDED TO BE USED AS /etc/zshrc, NOR WITHOUT
# EDITING!
#
# This file is based on ideas of:
#  Michael Prokop: <http://www.michael-prokop.at/computer/config/.zshrc>
#  Marijan Peh...: <http://free-po.hinet.hr/MarijanPeh/files/zshrc>
#  Adam Spiers...: <http://adamspiers.org/computing/shells/>
#
# Tested and used under {Net,Open}BSD, Slackware, Gentoo, Debian and LFS
# with Zsh 4.0.7, 4.0.9, 4.1.1, 4.2.0. 4.2.1, 4.2.4, 4.2.5 and 4.2.6.
#############################################################################

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

export DISABLE_AUTO_TITLE="true"
plugins=(zsh-autosuggestions zsh-syntax-highlighting zsh-editing-workbench command-not-found)
# git
# gitfast
# git-extras
# github
# last-working-dir
# per-directory-history
# sudo
# terminitor
# tmux
# tmuxinator
# Set name of the theme to load ~/.oh-my-zsh/themes/
## Good git theme
autoload is-at-least

            
for file in $ZSH/oh-my-zsh.sh   \
              ~/.zsh/zshexports   \
            ~/.zsh/zshoptions   \
            ~/.zsh/zshzle       \
            ~/.zsh/zshbindings  \
            ~/.zsh/zshcompctl   \
  ~/.zsh/zshcompctl.local   \
            ~/.zsh/zshstyle     \
            ~/.zsh/zshmisc      \
  ~/.zsh/zshaliases   \
  ~/.zsh/zshfunctions \
            ~/.zsh/zshhighlight \
            ~/.fzf.zsh          \
            ~/.zsh/z/z.sh       \
            ~/.zsh/fzf_funcs    \
            ~/.zsh/tmux_funcs   \
            ~/.zsh/zshlocal
    do
    # Test and then source some options
    if [ -f $file ]; then
            source $file
    else
            print "Note: $file is unavailable."
    fi
done

# LUA version of z. 
# https://github.com/skywind3000/z.lua with enhanced alogirthm and fzf support
eval "$(lua ${HOME}/.zsh/z.lua/z.lua --init zsh fzf )"
#cdpath=(.. ~ ~/src ~/zsh)
# Options to fzf command
# -x, --extended       Extended-search mode
export FZF_COMPLETION_OPTS='-x'
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

# Use hard limits, except for a smaller stack and no core dumps
unlimit
limit stack 8192
limit core 0
limit -s

umask 022

# Shell functions
setenv() { typeset -x "${1}${1:+=}${(@)argv[2,$#]}" }  # csh compatibility
freload() { while (( $# )); do; unfunction $1; autoload -U $1; shift; done }

# Where to look for autoloaded function definitions
fpath=($fpath ~/.zfunc ~/.zsh/zsh-completions-master/src )

# Autoload all shell functions from all directories in $fpath (following
# symlinks) that have the executable bit on (the executable bit is not
# necessary, but gives you an easy way to stop the autoloading of a
# particular shell function). $fpath should not be empty for this to work.
for func in $^fpath/*(N-.x:t); autoload $func

# automatically remove duplicates from these arrays
# typeset -U path cdpath fpath manpath

HISTSIZE=200
DIRSTACKSIZE=20

# Set/unset  shell options
setopt   notify globdots correct pushdtohome cdablevars autolist
setopt   autocd recexact longlistjobs
setopt   autoresume histignoredups pushdsilent noclobber
setopt   autopushd pushdminus extendedglob rcquotes mailwarning
unsetopt bgnice autoparamslash

# Disable Control-Q / Control-S
stty stop undef
stty start undef

# Autoload zsh modules when they are referenced
zmodload -a zsh/stat stat
zmodload -a zsh/zpty zpty
zmodload -a zsh/zprof zprof
zmodload -ap zsh/mapfile mapfile

## Need this for proper display of powerline-fonts
export LC_ALL=en_US.UTF-8

TRAPUSR1() {
  if [[ -o INTERACTIVE ]]; then
    {echo; echo Reload .zshrc } 1>&2
      source ~/.zshrc
  fi
}
#export THEME="Solarized (light)"
source ~/.zsh/zshtheme

#export BAT_THEME="Solarized (light)"
export BAT_THEME=GitHub

# TODO 2020-05-28 21:27 See if this is useful
# source /dpc/sfi/farm/sjlsfec1/conf/profile.lsf

alias sz_all="killall -USR1 zsh"

unsetenv XDG_RUNTIME_DIR

# Set DISPLAY
source ~/.display

### Ignoring history suggestions that match a pattern

export ZSH_AUTOSUGGEST_HISTORY_IGNORE="cd *"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=magenta"
#autoload zpty 
#export ZSH_AUTOSUGGEST_STRATEGY=(history completion)
#export ZSH_AUTOSUGGEST_STRATEGY=(completion)

#tmux select-pane -T ""

## Color for eza (ls replacement)
export EZA_COLORS="oc=38;5;12:xa=38;5;12"

# write bits
EZA_COLORS="${EZA_COLORS}:uw=38;5;12:gw=38;5;12:tw=38;5;12"
EZA_COLORS="${EZA_COLORS}:ur=38;5;12:gr=38;5;12:tr=38;5;12"
EZA_COLORS="${EZA_COLORS}:ux=38;5;12:gx=38;5;12:tx=38;5;12"
EZA_COLORS="${EZA_COLORS}:su=38;5;12:sf=38;5;12"
EZA_COLORS="${EZA_COLORS}:lp=38;5;6"
# nb  numbers of a file’s size if it is lower than 1 KB/Kib
# nk  numbers of a file’s size if it is between 1 KB/KiB and 1 MB/MiB
# nm  numbers of a file’s size if it is between 1 MB/MiB and 1 GB/GiB
# ng  numbers of a file’s size if it is between 1 GB/GiB and 1 TB/TiB
# nt  numbers of a file’s size if it is 1 TB/TiB or higher
EZA_COLORS="${EZA_COLORS}:nb=38;5;14:nk=38;5;12:nm=38;5;11:ng=38;5;1:nt=38;5;1;1"
# uu User if it is $USER
EZA_COLORS="${EZA_COLORS}:uu=38;5;14"
# da Date
EZA_COLORS="${EZA_COLORS}:da=38;5;6"
EZA_COLORS="${EZA_COLORS}:xx=38;5;7"
EZA_COLORS="${EZA_COLORS}:ln=38;5;3:lp=38;5;13"
EZA_COLORS="${EZA_COLORS}:ex=0"

## Colors are too light 2024-04-18 00:14 
# source ~/.oh-my-zsh/custom/plugins/fzf-tab/fzf-tab.plugin.zsh
## Need to load first
#disable-fzf-tab
# enable-fzf-tab
#tic -xe alacritty,alacritty-direct ~croysdal/local/extra/alacritty.info

